### ISSUE TITLE
Server execution error: {'type': 'invalid_prompt', 'message': 'Cannot execute because node ReferenceLatent does not exist.', 'details': "Node ID '#9'", 'extra_info': {}} (Error transferring http://127.0.0.1:8188/prompt - server replied: Bad Request)

### ISSUE THREAD

**Issue by Jantenario** [Acly/krita-ai-diffusion#1842]
Get this error when want to refine

**Comment by Jantenario** [comment]
Happens in ALL models, SDXL, S1.5 and Flux

**Comment by Jantenario** [comment]
Updated 10min ago, so issue in latest update

**Comment by Jantenario** [comment]
plugin version 1.36.0

**Comment by action1618** [comment]
Having the same problem, even with basic prompting no loras, barebones, attempted older proven kra files will not run. Any suggestions welcome. Last use of Krita Ai worked earlier in the week, so this was post update.

**Comment by Hekel1989** [comment]
Same here, exact same error. was working perfectly fine, updated to 1.36.0, everything stopped working (Illu,SDXL), nothing works, exact same error.
it is 100% something that broke with the new update

**Comment by Hekel1989** [comment]
just confirmed it's 1.36, I've re installed 1.35.1 manually, all working fine. so it's 100% update 1.36

**Comment by Acly** [comment]
Error should go away if you update ComfyUI to latest, although it may still produce wrong results.

Does this happen with manage server installs that were updated to 1.36.0?

**Comment by Hekel1989** [comment]
Mine is a managed server install, so, yes, correct

**Comment by Acly** [comment]
Bug should be fixed ([krita_ai_diffusion-1.36.1.zip](https://github.com/Acly/krita-ai-diffusion/releases/download/v1.36.0/krita_ai_diffusion-1.36.1.zip))

> Mine is a managed server install, so, yes, correct

Did you get a notifaction to upgrade the server after doing the plugin update? Sounds like that might something else that is broken, since it should've installed a version that has the node. I just tested it again with my managed server though and it worked fine, so not sure.

**Comment by Hekel1989** [comment]
> Bug should be fixed ([krita_ai_diffusion-1.36.1.zip](https://github.com/Acly/krita-ai-diffusion/releases/download/v1.36.0/krita_ai_diffusion-1.36.1.zip))
> 
> > Mine is a managed server install, so, yes, correct
> 
> Did you get a notifaction to upgrade the server after doing the plugin update? Sounds like that might something else that is broken, since it should've installed a version that has the node. I just tested it again with my managed server though and it worked fine, so not sure.

Yes, it updated through auto update, as it always did. I'll test the fix during the weekend, thanks!

**Comment by wantwon2** [comment]
Same problem. I can still generate images but trying anything with Flux Kontext gives this error. Updated to 1.36.1 and verified files on my managed server. No luck.

**Comment by aazj2024** [comment]
The same error occurs. Both ComfyUI and the components have been upgraded to the latest versions, but there is still an error in 1.361, while 1.35 works normally.

**Comment by Rogal80** [comment]
The same error occurs. Server execution error: {'type': 'invalid_prompt', 'message': 'Cannot execute because node ReferenceLatent does not exist.', 'details': "Node ID '#9'", 'extra_info': {}} (Error transferring http://127.0.0.1:8188/prompt - server replied: Bad Request)

**Comment by NoMansPC** [comment]
Same here. Plug-in version is 1.36.1 and it is locally managed (not a custom ComfyUI installation).

**Comment by Acly** [comment]
* if you get the error with a model other than Flux Kontext, update plugin to 1.35.1
* if you get the error with Kontext & custom ComfyUI, update ComfyUI
* if you get the error with Kontext & managed server, try to reinstall the server (seems like it didn't update automatically)

**Comment by wantwon2** [comment]
> * if you get the error with a model other than Flux Kontext, update plugin to 1.35.1
> 
>     * if you get the error with Kontext & custom ComfyUI, update ComfyUI
> 
>     * if you get the error with Kontext & managed server, try to reinstall the server (seems like it didn't update automatically)

I was having the third problem and this resolved it. Note for other users: Move your models folder to another location first. You can't reinstall the server with ANY files left in the original folder. Your style presets are manged by Krita and don't need to be backed up.

Thanks for the fix. Looking forward to trying this model.

**Comment by Hekel1989** [comment]
> * if you get the error with a model other than Flux Kontext, update plugin to 1.35.1
> * if you get the error with Kontext & custom ComfyUI, update ComfyUI
> * if you get the error with Kontext & managed server, try to reinstall the server (seems like it didn't update automatically)

Pardon the silly question, but how do we go about updating managed comfy ui the correct way?

**Comment by NoMansPC** [comment]
> * if you get the error with a model other than Flux Kontext, update plugin to 1.35.1
> 
>     * if you get the error with Kontext & custom ComfyUI, update ComfyUI
> 
>     * if you get the error with Kontext & managed server, try to reinstall the server (seems like it didn't update automatically)

I can confirm that reinstalling everything worked. Took more work than I wanted, though.

**Comment by Hekel1989** [comment]
I'm feeling very silly, but I've updated to 1.36.1, now SDXL/1.5 work as inteded, but I cannot get Flux Kontext to even appear?
The folders you listed in your release notes don't exist in my managed server, and I see no option to enable Flux Kontext anywhere in the UI?
```
Model download (manual)

    [flux1-dev-kontext_fp8_scaled.safetensors] → **/models/diffusion_models**

Also needed in case you don't have them already for Flux:

    [ae.safetensors] → /models/vae
    [clip_l.safetensors] → /models/text_encoders
    [t5xxl_fp8_e4m3fn_scaled.safetensors] → /models/text_encoders
```

I've got no **text_encoders nor diffusion_models** folder ins my /models folder, unless you're referring to /comfyui/models?
Even if that's the case, I've added all the files in there, and I've still got no Flux Kontext.
Am I missing something? I can't test whether it works or not with Flux as I can't get Flux Kontext to appear.

Thanks

**Comment by Hekel1989** [comment]
Ok, I've re-installed everything (deleted the whole ai-diffusion folder, re installed 1.36.1, re installed the whole managed server), SDXL, etc work fine, but still no Flux Kontext. Absolutely no idea what I'm doing wrong.

**Comment by rusandy-SPB** [comment]
Friends. Help with the problem that everyone is discussing about the work of Crete and the Flux Kontext model.
Installed module 1.36.1. Но появляется точно такая  же ошибка:
Ошибка выполнения сервера: {'type': 'invalid_prompt', 'message': 'Cannot execute because node ReferenceLatent does not exist.', 'details': "Node ID '#9'", 'extra_info': {}} (Error transferring http://127.0.0.1:8188/prompt - server replied: Bad Request)
What are my actions? If I may, in detail, please?

![Image](https://github.com/user-attachments/assets/4359acf3-0ea3-49be-bd28-1a54147b109e)

**Comment by feureau** [comment]
version 1.36.1. having the same problem. Also, I don't know if this is related, but since there's no style preset for kontext, i just copied the regular flux preset and change the settings manually. Is this correct?

![Image](https://github.com/user-attachments/assets/e0337628-8167-47fe-a9d9-6a15145480eb)

**Comment by rusandy-SPB** [comment]
> Версия 1.36.1. Та же проблема. Кроме того, я не знаю, связано ли это с этим, но поскольку для Kontext нет предустановленного стиля, я просто скопировал обычный предустановленный стиль Flux и изменил настройки вручную. Правильно ли я сделал?
> 

I did the same thing. 
I selected the settings as for a regular Flux. The result is shown in the post above yours

**Comment by eromaxi** [comment]
Guys, I've encountered the same error and followed the advice to reinstall the server to get Flux Kontext working. However, I'm now stuck because the server installation doesn't occur; clicking the Install button has no effect. Restarting Krita doesn't help. What to do?

![Image](https://github.com/user-attachments/assets/f262e57a-1f43-4eff-982b-ca6a33627b80)

**Comment by Hekel1989** [comment]
> Guys, I've encountered the same error and followed the advice to reinstall the server to get Flux Kontext working. However, I'm now stuck because the server installation doesn't occur; clicking the Install button has no effect. Restarting Krita doesn't help. What to do?
> 
> ![Image](https://github.com/user-attachments/assets/f262e57a-1f43-4eff-982b-ca6a33627b80)

You've got files in your models folder, that's why it won't reinstall.

Move your models folder somewhere else, and try again, and it will work.

**Comment by eromaxi** [comment]
> > Guys, I've encountered the same error and followed the advice to reinstall the server to get Flux Kontext working. However, I'm now stuck because the server installation doesn't occur; clicking the Install button has no effect. Restarting Krita doesn't help. What to do?
> > ![Image](https://github.com/user-attachments/assets/f262e57a-1f43-4eff-982b-ca6a33627b80)
> 
> You've got files in your models folder, that's why it won't reinstall.
> 
> Move your models folder somewhere else, and try again, and it will work.

I followed your advice and moved the models folder to a different location, but no, it doesn't install. Is there any other workaround?

**Comment by Hekel1989** [comment]
> > > Guys, I've encountered the same error and followed the advice to reinstall the server to get Flux Kontext working. However, I'm now stuck because the server installation doesn't occur; clicking the Install button has no effect. Restarting Krita doesn't help. What to do?
> > > ![Image](https://github.com/user-attachments/assets/f262e57a-1f43-4eff-982b-ca6a33627b80)
> > 
> > You've got files in your models folder, that's why it won't reinstall.
> > 
> > Move your models folder somewhere else, and try again, and it will work.
> 
> I followed your advice and moved the models folder to a different location, but no, it doesn't install. Is there any other workaround?

Click on view log files, it will tell you why it's not reinstalling. Guaranteed you've got one file you forgot about in ComfyUI/models :)

**Comment by eromaxi** [comment]
> > > > Guys, I've encountered the same error and followed the advice to reinstall the server to get Flux Kontext working. However, I'm now stuck because the server installation doesn't occur; clicking the Install button has no effect. Restarting Krita doesn't help. What to do?
> > > > ![Image](https://github.com/user-attachments/assets/f262e57a-1f43-4eff-982b-ca6a33627b80)
> > > 
> > > 
> > > You've got files in your models folder, that's why it won't reinstall.
> > > Move your models folder somewhere else, and try again, and it will work.
> > 
> > 
> > I followed your advice and moved the models folder to a different location, but no, it doesn't install. Is there any other workaround?
> 
> Click on view log files, it will tell you why it's not reinstalling. Guaranteed you've got one file you forgot about in ComfyUI/models :)

For some reason, there was no ComfyUI folder there, so I ended up removing the server folder altogether. Installation completed and I brought back the model's folder. Kontext works, but mixed results so far.

**Comment by musti1974** [comment]
> Freunde. Hilfe bei dem Problem, das jeder über die Arbeit Kretas und des Flux-Klempressionsmodells diskutiert. Installiertes Modul 1.36.1. - - - - - - -: "Typ": "invalid-prompt", "Nachricht": "Kann nicht ausführen, weil Node ReferenceLatent nicht existiert"., 'Details': "Node ID ['9](https://github.com/Acly/krita-ai-diffusion/pull/9) '", 'extra'info':' (Error übertragen [http://127.0.:8188/prompt](http://127.0.0.1:8188/prompt) - server repliziert: Bad Request) Was sind meine Handlungen? Wenn ich im Detail darf, bitte?
> 
> ![Image](https://github.com/user-attachments/assets/4359acf3-0ea3-49be-bd28-1a54147b109e)

habe auch das gleiche problem

**Comment by markstraw** [comment]
I was also getting this error even though I had updated Krita and had updated to 1.36.1 for a Flux prompt. 

Thanks to comments on this thead, I deleted and then reinstalled Server and don't get the error anymore.

**Comment by rusandy-SPB** [comment]
> Thanks to the comments on this topic, i **_*_ deleted and then reinstalled Server_*_** and the error no longer appears.
Explain in more detail what exactly did you delete (folder or files)? And how did you REINSTALL the server after that? 
have you launched Krita in a new way?

**Comment by markstraw** [comment]
> > Thanks to the comments on this topic, i **_*_ deleted and then reinstalled Server_*_** and the error no longer appears.
> > Explain in more detail what exactly did you delete (folder or files)? And how did you REINSTALL the server after that?
> > have you launched Krita in a new way?

Krita launched normally. 
Under Configuration > Connection, select Manage > Delete. 
Reselect models then click Install. 
Make sure it is Plugin version 1.36.1 or [latest](https://github.com/Acly/krita-ai-diffusion/releases/download/v1.36.0/krita_ai_diffusion-1.36.1.zip)

**Comment by rusandy-SPB** [comment]
> Krita started up normally. In the Configuration section> Connect, select Management> Remove. Re-select the models, then click Install. Make sure that this is the plugin version 1.36.1
_...Everything turned out great._ 
**Thank you for your help!.** I want to clarify an important point:
when choosing a SAMPLER, you need to select the desired option from the list ⚡No. 3 in the figure.

<img width="1200" height="923" alt="Image" src="https://github.com/user-attachments/assets/e6e754ed-fa87-4c0c-92cf-cc79196bbc9e" />

**Comment by rusandy-SPB** [comment]
examples of working with in the "image replacement" mode

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/2cd15a5c-259e-44db-8322-b36fbbf0eec6" />

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/0a7204a6-2d38-4e67-9019-5b584f7a6749" />

**Comment by rusandy-SPB** [comment]
examples of Flux's work on changing clothes in an image and turning a PHOTO into a black-and-white drawing **_(a particularly successful solution!_** 😉👌
<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/d8d4d05b-61a3-4487-b5c7-9148fe65a661" />

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/5678f083-ce59-48af-9077-234036e1d6a8" />

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/aa24e0a1-fb65-48e6-a269-a4add8ca6a07" />
