### ISSUE TITLE
NunchakuFluxDiTLoader does not exist

### ISSUE THREAD

**Issue by longkinght** [Acly/krita-ai-diffusion#1965]
Server error: {'type': 'invalid_prompt', 'message': 'Cannot execute because node NunchakuFluxDiTLoader does not exist.', 'details': "Node ID '#1'", 'extra_info': {}} (Error transferring http://127.0.0.1:8188/prompt - server replied: Bad Request)

There is already a Nunchaku model that works properly in comfyui and has been recognized, but it reports an error when running in Krita.

<img width="771" height="99" alt="Image" src="https://github.com/user-attachments/assets/494a639b-7051-4489-bde3-0f3ac05f58cf" />

**Comment by Acly** [comment]
Not sure how you're running nunchaku, but the plugin requires these nodes: https://github.com/nunchaku-tech/ComfyUI-nunchaku

which include NunchakuFluxDiTLoader

**Comment by jdcsen** [comment]
Can confirm: encountered this issue due to missing ComfyUI-nunchaku. Note that I also had to run [the command to install the backend](https://nunchaku.tech/docs/ComfyUI-nunchaku/get_started/installation.html#step-2-install-the-nunchaku-backend) to resolve this error. Not typical of other ComfyUI nodes I've used, so worth pointing out.

**Comment by longkinght** [comment]
> Not sure how you're running nunchaku, but the plugin requires these nodes: https://github.com/nunchaku-tech/ComfyUI-nunchaku不确定您是如何运行双节棍的，但该插件需要以下节点：https://github.com/nunchaku-tech/ComfyUI-nunchaku
> 
> which include NunchakuFluxDiTLoader其中包括 NunchakuFluxDiTLoader

Yes, after checking, I found that I had installed nunchaku from another branch. After switching back to the main plugin, it worked fine. thanks

**Comment by mickey9801** [comment]
I have try to reinstall the comfyUI, ComfyUI Manager, ComfyUI-nunchaku and nunchaku backend again and again, manual or thru ComfyUI Manager, but some Nunchaku still not found. Hope someone could help.

The version I am using are:

ComfyUI windows portable nvidia v3.70
python 3.13.9
pytorch 2.9.0+cu130
ComfyUI Manager v3.37.1
Nunchaku 1.0.2 (nunchaku-1.0.2+torch2.9-cp313-cp313-win_amd64.whl)
comfyui-nunchaku 1.0.2

**Comment by mekler22** [comment]
Same here. Flux Kontext when trying to use (In Linux, with a separate docker for comfyui, and kontext works fine inside it), gives same error to do with nunchaku.

**Comment by feureau** [comment]
Hi, I’m also experiencing the same issue:

```
Server error: {'type': 'invalid_prompt', 'message': 'Cannot execute because node NunchakuFluxDiTLoader does not exist.', 'details': "Node ID '#1'", 'extra_info': {}}
```

I am using Krita AI plugin **v1.45.0** with the **default ComfyUI installed by the plugin**. All fresh installs. It seems the plugin cannot find the `NunchakuFluxDiTLoader` node, and the error occurs whenever I try to run a workflow using Flux.

Has anyone found a way to get this node recognized, or is there a required additional node package that needs to be installed?

**Comment by Acly** [comment]
See also #2256 

Potential causes so far:
* installing the "Face" control models breaks nunchaku nodes
* incompatible CUDA version on Linux

**Comment by viba1** [comment]
Same problem here since KritaAI update (local managed server). Krita 5.2.14 / AI 1..45.0 / Cuda 13.1.

Complete re-install (from scratch) of krita and kritaAI doesn't fix the issue. 

This appears to be a poor integration of nunchaku-ai within the latest KritaAI.
=> How do they test this?

**Comment by Acly** [comment]
Re-install will only work if it's not the Linux/CUDA problem. I can't tell without seeing a server.log

It works / is tested on windows, linux tests don't have a NVIDIA gpu available atm so they can't test nunchaku

For those who use custom servers: if the node is not found, it means Nunchaku nodes failed to load and you need to check and fix it

**Comment by anigroove** [comment]
My server log says:
ComfyUI-nunchaku 1.0.1 is not compatible with nunchaku 1.0.1. Please update nunchaku to a supported version in ['v1.0.0'].

There is a  . (point) mismatch ?   version 1.0.1

**Comment by jfcantu** [comment]
Hey folks,

Stumbled on this issue by accident while trying to get Nunchaku up and running.

If you check your Comfy server logs, you may see an error about `libcudart.so.13` not being found, which will cause Nunchaku to fail to load. For whatever reason, installing Pytorch for CUDA 13 didn't help me.

However, installing the CUDA Toolkit v13 directly should solve the issue: https://developer.nvidia.com/cuda-downloads

**Comment by mekler22** [comment]
> My server log says: ComfyUI-nunchaku 1.0.1 is not compatible with nunchaku 1.0.1. Please update nunchaku to a supported version in ['v1.0.0'].
> 
> There is a . (point) mismatch ? version 1.0.1

did you install using the install wheel json from inside comfyui?

**Comment by anigroove** [comment]
I used the [topic]  Krita ai diffusion plugin  installer.
Always worked fine.

**Comment by Ian1971** [comment]
I found 1.2.1 would not install correctly but installed 1.2.0 via install wheel

**Comment by tommywright** [comment]
Still broken. Why use this node anyway? So many issues with it on comfyui also. :(

**Comment by blackxCMD-jpg** [comment]
If you have a problem with Krita, with the application running, you can go to the browser at http://127.0.0.1:8188/ and on the right there will be a sign - download Krita workflow, and you will see the problem highlighted in red. 

in terminal: pip install -U --pre comfyui-manager
or:
Go to ComfyUI/custom_nodes dir in terminal (cmd)
git clone https://github.com/ltdrdata/ComfyUI-Manager comfyui-manager
Restart ComfyUI
NFO: https://github.com/comfy-org/ComfyUI-Manager

In comfyui, go to the manager and in the bottom right corner, select check missing, select comfyui-nunchaku, install - restart
