### ISSUE TITLE
Text encoders / VAE models  (Qwen, Flux) not found in 1.40.0

### ISSUE THREAD

**Issue by JasonS09** [Acly/krita-ai-diffusion#2082]
Hello, I have installed Qwen according to: https://github.com/Acly/krita-ai-diffusion/discussions/2081

However the model is not found.

Here is my diffusion_models folder:

<img width="1038" height="380" alt="Image" src="https://github.com/user-attachments/assets/c247e550-2f34-4038-90cb-a9935810b527" />

Here is my text_encoders folder:

<img width="784" height="261" alt="Image" src="https://github.com/user-attachments/assets/716d1d4e-58d9-4c20-bcdb-4fbabef57aaa" />

This shows when I connect to the server:

<img width="951" height="424" alt="Image" src="https://github.com/user-attachments/assets/f414a93d-af62-4e58-b6d8-cfb9ed1966f3" />

**Comment by nakanakapoi** [comment]
Also happen to me, already have the models and updated everything. Hoping for fix soon.

**Comment by Acly** [comment]
Fixed here: https://github.com/Acly/krita-ai-diffusion/commit/785c26f86abb7dd0183b59b3f47f61867458eb76

Possible workarounds (either one should work):
* install [ComfyUI-GGUF](https://github.com/city96/ComfyUI-GGUF) nodes (just need the nodes, no extra models)
* use latest version of the plugin from GIT
* apply the patch above manually
* revert to previous plugin version

**Comment by shadowlocked** [comment]
> install [ComfyUI-GGUF](https://github.com/city96/ComfyUI-GGUF) nodes (just need the nodes, no extra models)

This was what worked for me.

**Comment by pmads87** [comment]
After updating to 1.4.0 I get this when trying to load Flux:
`size mismatch for shared.weight: copying a param with shape torch.Size([256384, 4096]) from checkpoint, the shape in current model is torch.Size([32128, 4096]).`

Also, for SDXL and Illustrious, clip_g seem to be missing all of a sudden:
`Exception: Text Encoder 'clip_g' for SD XL not found`
`Exception: Text Encoder 'clip_g' for Illustrious not found`

I tried manually downloading [this version ](https://huggingface.co/Comfy-Org/stable-diffusion-3.5-fp8/blob/main/text_encoders/clip_g.safetensors) of clip_g, placing it in /text_encoders/clip_g.safetensor. Now the model loads and generates, but the images look... horrendous.

For me, only Qwen works.

**Comment by momokyara** [comment]
> Fixed here:   修复于此：[785c26f](https://github.com/Acly/krita-ai-diffusion/commit/785c26f86abb7dd0183b59b3f47f61867458eb76)
> 
> Possible workarounds (either one should work):可能的解决方法（任何一个都可以）：
> 
> * install [ComfyUI-GGUF](https://github.com/city96/ComfyUI-GGUF) nodes (just need the nodes, no extra models)安装 [ComfyUI-GGUF](https://github.com/city96/ComfyUI-GGUF) 节点（只需要节点，不需要额外的模型）
> * use latest version of the plugin from GIT使用 GIT 中最新版本的插件
> * apply the patch above manually手动应用上述补丁
> * revert to previous plugin version恢复到之前的插件版本

I have followed all the steps above, but the problem still exists

<img width="1152" height="825" alt="Image" src="https://github.com/user-attachments/assets/fe0d0c72-f967-4201-bf59-a9f7ccc16944" />

<img width="1125" height="681" alt="Image" src="https://github.com/user-attachments/assets/ffe539dc-1964-4f5f-b386-501d4b635e86" />

<img width="1125" height="681" alt="Image" src="https://github.com/user-attachments/assets/2ad1e432-13f6-48a4-a1a5-4314f1bfe6a3" />

<img width="811" height="461" alt="Image" src="https://github.com/user-attachments/assets/c7cc1626-c9aa-418f-a996-04f5cd7b8023" />

**Comment by Acly** [comment]
@pmads87 For SDXL/Illustrious you should just put the models in `checkpoints` folder, they usually have Clip-G integrated and there is no need to download it separately

**Comment by Acly** [comment]
Fixed in [1.40.1](https://github.com/Acly/krita-ai-diffusion/releases)
