### ISSUE TITLE
Error Installing Managed Server (Linux/macOS), failed to build pycairo

### ISSUE THREAD

**Issue by J35-Sudo** [Acly/krita-ai-diffusion#2134]
System Info

Linux Mint 22.1 Cinnamon
NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate]
AMD Ryzen 7 3700X 8-Core Processor × 8
Krita 5.2.13

**What appears to be the issue**: I was using the previous version of krita diffusion (installed 2 weeks ago) on a fresh up to date flatpak version of krita with no issue. When installing this most recent update the installation fails during the PyCairo package build phase according to the log below. The error occurs (I think) because the required C compiler (e.g., gcc, clang) is missing or not install correctly. I'm using a fresh install of krita (the flatpak verson). I tried purging and reinstall krita diffusion plugin and purging, reinstalling kirta with no luck.

---

**Log Output**

```
2025-11-03 19:36:46,239 INFO Loaded 13 sampler presets from /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/presets/samplers.json
2025-11-03 19:36:46,323 INFO Extension initialized, Version: 1.41.0, Python: 3.10.19 (main, Nov 11 2011, 11:11:11) [GCC 15.2.0]
2025-11-03 19:36:46,526 INFO Checking for latest plugin version at https://api.interstice.cloud
2025-11-03 19:36:46,965 INFO Connecting to http://127.0.0.1:8188
2025-11-03 19:36:47,345 INFO Plugin is up to date!
2025-11-03 19:36:52,155 INFO Connecting to http://127.0.0.1:8000
2025-11-03 19:37:45,692 INFO Installation started in /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server
2025-11-03 19:37:45,695 INFO Downloading https://astral.sh/uv/0.8.12/install.sh to /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/.cache/install_uv.sh
2025-11-03 19:37:46,134 INFO Executing /bin/sh /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/.cache/install_uv.sh
2025-11-03 19:37:47,511 INFO no checksums to verify
2025-11-03 19:37:47,711 INFO installing to /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/uv
2025-11-03 19:37:47,791 INFO uv
2025-11-03 19:37:47,811 INFO uvx
2025-11-03 19:37:47,811 INFO everything's installed!
2025-11-03 19:37:47,831 INFO 
2025-11-03 19:37:47,831 INFO To add $HOME/.var/app/org.kde.krita/data/krita/ai_diffusion/server/uv to your PATH, either restart your shell or run:
2025-11-03 19:37:47,832 INFO 
2025-11-03 19:37:47,832 INFO source $HOME/.var/app/org.kde.krita/data/krita/ai_diffusion/server/uv/env (sh, bash, zsh)
2025-11-03 19:37:47,832 INFO source $HOME/.var/app/org.kde.krita/data/krita/ai_diffusion/server/uv/env.fish (fish)
2025-11-03 19:37:47,911 INFO Installed uv at /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/uv/uv
2025-11-03 19:37:47,911 INFO Creating venv in /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/venv
2025-11-03 19:37:47,911 INFO Executing /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/uv/uv venv --python 3.12 /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/venv
2025-11-03 19:37:50,531 INFO Using uv: uv 0.8.12
2025-11-03 19:37:50,711 INFO Using Python: Python 3.12.11, /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/venv/bin/python3
2025-11-03 19:37:50,711 INFO Downloading https://github.com/comfyanonymous/ComfyUI/archive/f2bb3230b796f6a486894fc3b597db2c0b9538c9.zip to /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/.cache/ComfyUI-f2bb3230b796f6a486894fc3b597db2c0b9538c9.zip
2025-11-03 19:37:51,493 INFO Extracting /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/.cache/ComfyUI-f2bb3230b796f6a486894fc3b597db2c0b9538c9.zip to /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server
2025-11-03 19:37:51,679 INFO Executing /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/uv/uv pip install -U torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu128
2025-11-03 19:40:30,625 INFO Executing /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server/uv/uv pip install -r /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/server_requirements.txt
2025-11-03 19:40:38,565 ERROR Error during installation: Using Python 3.12.11 environment at: venv
Resolved 132 packages in 2.04s
Downloading jaxlib (77.4MiB)
Downloading av (38.7MiB)
Downloading opencv-python (60.1MiB)
Downloading mediapipe (34.0MiB)
Downloading scikit-learn (9.0MiB)
Downloading matplotlib (8.3MiB)
Downloading transformers (11.4MiB)
Downloading pydantic-core (2.0MiB)
Downloading lxml (5.0MiB)
Downloading opencv-contrib-python (65.9MiB)
Downloading scikit-image (14.3MiB)
Downloading opencv-python-headless (47.7MiB)
Downloading ctranslate2 (37.0MiB)
Downloading kiwisolver (1.4MiB)
Downloading jax (2.7MiB)
Downloading aiohttp (1.7MiB)
Downloading sentencepiece (1.2MiB)
Downloading numpy (17.1MiB)
Downloading kornia (1.0MiB)
Downloading reportlab (1.9MiB)
Downloading tokenizers (3.1MiB)
Downloading soundfile (1.3MiB)
Downloading diffusers (3.9MiB)
Downloading simsimd (1.0MiB)
Downloading hf-xet (3.2MiB)
Downloading scipy (34.0MiB)
Downloading ml-dtypes (4.7MiB)
Downloading fonttools (4.7MiB)
Downloading kornia-rs (2.6MiB)
   Building sacremoses==0.0.53
   Building antlr4-python3-runtime==4.9.3
   Building fvcore==0.1.5.post20221221
   Building iopath==0.1.10
      Built iopath==0.1.10
      Built fvcore==0.1.5.post20221221
      Built antlr4-python3-runtime==4.9.3
 Downloading kornia
 Downloading simsimd
      Built sacremoses==0.0.53
 Downloading soundfile
 Downloading sentencepiece
 Downloading kiwisolver
   Building pycairo==1.28.0
 Downloading aiohttp
 Downloading reportlab
 Downloading pydantic-core
 Downloading kornia-rs
 Downloading jax
 Downloading tokenizers
 Downloading hf-xet
 Downloading diffusers
 Downloading ml-dtypes
 Downloading fonttools
 Downloading lxml
  Ã Failed to build `pycairo==1.28.0`
  âââ¶ The build backend returned an error
  â°ââ¶ Call to `mesonpy.build_wheel` failed (exit status: 1)

      [stdout]
      + meson setup
      /home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src
      /home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src/.mesonpy-ydksp6hr
      -Dbuildtype=release -Db_ndebug=if-release
      -Db_vscrt=md -Dwheel=true -Dtests=false
      --native-file=/home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src/.mesonpy-ydksp6hr/meson-python-native-file.ini
      The Meson build system
      Version: 1.9.1
      Source dir:
      /home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src
      Build dir:
      /home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src/.mesonpy-ydksp6hr
      Build type: native build
      Project name: pycairo
      Project version: 1.28.0

      ../meson.build:1:0: ERROR: Unknown compiler(s): [['cc'], ['gcc'],
      ['clang'], ['nvc'], ['pgcc'], ['icc'], ['icx']]
      The following exception(s) were encountered:
      Running `cc --version` gave "[Errno 2] No such file or directory: 'cc'"
      Running `gcc --version` gave "[Errno 2] No such file or directory:
      'gcc'"
      Running `clang --version` gave "[Errno 2] No such file or directory:
      'clang'"
      Running `nvc --version` gave "[Errno 2] No such file or directory:
      'nvc'"
      Running `pgcc --version` gave "[Errno 2] No such file or directory:
      'pgcc'"
      Running `icc --version` gave "[Errno 2] No such file or directory:
      'icc'"
      Running `icx --version` gave "[Errno 2] No such file or directory:
      'icx'"

      A full log can be found at
      /home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src/.mesonpy-ydksp6hr/meson-logs/meson-log.txt

      hint: This usually indicates a problem with the package or the build
      environment.
  help: `pycairo` (v1.28.0) was included because `svglib` (v1.6.0) depends on
        `rlpycairo` (v0.4.0) which depends on `pycairo`
Traceback (most recent call last):
  File "/home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/server.py", line 352, in install
    await self._install(cb)
  File "/home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/server.py", line 179, in _install
    await try_install(comfy_dir, self._install_comfy, comfy_dir, network, cb)
  File "/home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/server.py", line 803, in try_install
    raise e
  File "/home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/server.py", line 798, in try_install
    await installer(*args)
  File "/home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/server.py", line 267, in _install_comfy
    await self._pip_install("ComfyUI", ["-r", str(requirements_txt)], cb)
  File "/home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/server.py", line 792, in _execute_process
    raise Exception(_("Error during installation") + f": {errlog}")
Exception: Error during installation: Using Python 3.12.11 environment at: venv
Resolved 132 packages in 2.04s
Downloading jaxlib (77.4MiB)
Downloading av (38.7MiB)
Downloading opencv-python (60.1MiB)
Downloading mediapipe (34.0MiB)
Downloading scikit-learn (9.0MiB)
Downloading matplotlib (8.3MiB)
Downloading transformers (11.4MiB)
Downloading pydantic-core (2.0MiB)
Downloading lxml (5.0MiB)
Downloading opencv-contrib-python (65.9MiB)
Downloading scikit-image (14.3MiB)
Downloading opencv-python-headless (47.7MiB)
Downloading ctranslate2 (37.0MiB)
Downloading kiwisolver (1.4MiB)
Downloading jax (2.7MiB)
Downloading aiohttp (1.7MiB)
Downloading sentencepiece (1.2MiB)
Downloading numpy (17.1MiB)
Downloading kornia (1.0MiB)
Downloading reportlab (1.9MiB)
Downloading tokenizers (3.1MiB)
Downloading soundfile (1.3MiB)
Downloading diffusers (3.9MiB)
Downloading simsimd (1.0MiB)
Downloading hf-xet (3.2MiB)
Downloading scipy (34.0MiB)
Downloading ml-dtypes (4.7MiB)
Downloading fonttools (4.7MiB)
Downloading kornia-rs (2.6MiB)
   Building sacremoses==0.0.53
   Building antlr4-python3-runtime==4.9.3
   Building fvcore==0.1.5.post20221221
   Building iopath==0.1.10
      Built iopath==0.1.10
      Built fvcore==0.1.5.post20221221
      Built antlr4-python3-runtime==4.9.3
 Downloading kornia
 Downloading simsimd
      Built sacremoses==0.0.53
 Downloading soundfile
 Downloading sentencepiece
 Downloading kiwisolver
   Building pycairo==1.28.0
 Downloading aiohttp
 Downloading reportlab
 Downloading pydantic-core
 Downloading kornia-rs
 Downloading jax
 Downloading tokenizers
 Downloading hf-xet
 Downloading diffusers
 Downloading ml-dtypes
 Downloading fonttools
 Downloading lxml
  Ã Failed to build `pycairo==1.28.0`
  âââ¶ The build backend returned an error
  â°ââ¶ Call to `mesonpy.build_wheel` failed (exit status: 1)

      [stdout]
      + meson setup
      /home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src
      /home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src/.mesonpy-ydksp6hr
      -Dbuildtype=release -Db_ndebug=if-release
      -Db_vscrt=md -Dwheel=true -Dtests=false
      --native-file=/home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src/.mesonpy-ydksp6hr/meson-python-native-file.ini
      The Meson build system
      Version: 1.9.1
      Source dir:
      /home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src
      Build dir:
      /home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src/.mesonpy-ydksp6hr
      Build type: native build
      Project name: pycairo
      Project version: 1.28.0

      ../meson.build:1:0: ERROR: Unknown compiler(s): [['cc'], ['gcc'],
      ['clang'], ['nvc'], ['pgcc'], ['icc'], ['icx']]
      The following exception(s) were encountered:
      Running `cc --version` gave "[Errno 2] No such file or directory: 'cc'"
      Running `gcc --version` gave "[Errno 2] No such file or directory:
      'gcc'"
      Running `clang --version` gave "[Errno 2] No such file or directory:
      'clang'"
      Running `nvc --version` gave "[Errno 2] No such file or directory:
      'nvc'"
      Running `pgcc --version` gave "[Errno 2] No such file or directory:
      'pgcc'"
      Running `icc --version` gave "[Errno 2] No such file or directory:
      'icc'"
      Running `icx --version` gave "[Errno 2] No such file or directory:
      'icx'"

      A full log can be found at
      /home/NYNAMEDIR/.var/app/org.kde.krita/cache/uv/sdists-v9/pypi/pycairo/1.28.0/LxX4K2euOr9O7o5lxptTF/src/.mesonpy-ydksp6hr/meson-logs/meson-log.txt

      hint: This usually indicates a problem with the package or the build
      environment.
  help: `pycairo` (v1.28.0) was included because `svglib` (v1.6.0) depends on
        `rlpycairo` (v0.4.0) which depends on `pycairo`

2025-11-03 19:40:38,566 ERROR Installation failed
2025-11-03 19:40:38,566 INFO Found server installation vincomplete at /home/NYNAMEDIR/.var/app/org.kde.krita/data/krita/ai_diffusion/server
```

**Comment by runrunrirun** [comment]
Same pycairo install failure on macOS 15.7.1 and Krita 5.2.11

**Comment by Acly** [comment]
It doesn't look like pycairo provides binary packages.

Building should work on Linux (probably macOS too) if build tools are installed. But this is never the case for Flatpak as it runs in a sandbox.

Not sure yet why it wasn't an issue before (pycairo version is not new), maybe it just wasn't needed at all...

**Comment by Acly** [comment]
It seems like pycairo was introduced in latest version of svglib.

You could try to find [server_requirements.txt](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/server_requirements.txt#L36) and edit line 36 
```
svglib==1.6.0
```
change to
```
svglib==1.5.1
```
Then try to re-install the server.

File is located in ~/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion for flatpak
otherwise ~/.local/share/krita/pykrita/ai_diffusion

**Comment by runrunrirun** [comment]
I actually have build tools installed as well as the other dependencies locally but this apparently uses its own venv and apparently expects packages it doesn't have there so idk fuck Python dependency management entirely :/ 

    raise Exception(_("Error during installation") + f": {errlog}")
Exception: Error during installation: Using Python 3.12.9 environment at: venv
Resolved 117 packages in 26ms
   Building pycairo==1.28.0
  × Failed to build `pycairo==1.28.0`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `mesonpy.build_wheel` failed (exit status: 1)

      [stdout]
      + meson setup
      /Users/fred/.cache/uv/sdists-v9/pypi/pycairo/1.28.0/VjMuQu-pihe9WKWKqRcLC/src
      /Users/fred/.cache/uv/sdists-v9/pypi/pycairo/1.28.0/VjMuQu-pihe9WKWKqRcLC/src/.mesonpy-9ta56zsc
      -Dbuildtype=release -Db_ndebug=if-release
      -Db_vscrt=md -Dwheel=true -Dtests=false
      --native-file=/Users/fred/.cache/uv/sdists-v9/pypi/pycairo/1.28.0/VjMuQu-pihe9WKWKqRcLC/src/.mesonpy-9ta56zsc/meson-python-native-file.ini
      The Meson build system
      Version: 1.9.1
      Source dir:
      /Users/fred/.cache/uv/sdists-v9/pypi/pycairo/1.28.0/VjMuQu-pihe9WKWKqRcLC/src
      Build dir:
      /Users/fred/.cache/uv/sdists-v9/pypi/pycairo/1.28.0/VjMuQu-pihe9WKWKqRcLC/src/.mesonpy-9ta56zsc
      Build type: native build
      Project name: pycairo
      Project version: 1.28.0
      C compiler for the host machine: cc (clang 17.0.0 "Apple clang version
      17.0.0 (clang-1700.3.19.1)")
      C linker for the host machine: cc ld64 1221.4
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Program python3 found: YES
      (/Users/fred/.cache/uv/builds-v0/.tmpuefBJ1/bin/python)
      Compiler for C supports arguments -Wall: YES
      Compiler for C supports arguments -Warray-bounds: YES
      Compiler for C supports arguments -Wcast-align: YES
      Compiler for C supports arguments -Wconversion: YES
      Compiler for C supports arguments -Wextra: YES
      Compiler for C supports arguments -Wformat=2: YES
      Compiler for C supports arguments -Wformat-nonliteral: YES
      Compiler for C supports arguments -Wformat-security: YES
      Compiler for C supports arguments -Wimplicit-function-declaration: YES
      Compiler for C supports arguments -Winit-self: YES
      Compiler for C supports arguments -Winline: YES
      Compiler for C supports arguments -Wmissing-format-attribute: YES
      Compiler for C supports arguments -Wmissing-noreturn: YES
      Compiler for C supports arguments -Wnested-externs: YES
      Compiler for C supports arguments -Wold-style-definition: YES
      Compiler for C supports arguments -Wpacked: YES
      Compiler for C supports arguments -Wpointer-arith: YES
      Compiler for C supports arguments -Wreturn-type: YES
      Compiler for C supports arguments -Wshadow: YES
      Compiler for C supports arguments -Wsign-compare: YES
      Compiler for C supports arguments -Wstrict-aliasing: YES
      Compiler for C supports arguments -Wundef: YES
      Compiler for C supports arguments -Wunused-but-set-variable: YES
      Compiler for C supports arguments -Wswitch-default: YES
      Compiler for C supports arguments -Wno-missing-field-initializers: YES
      Compiler for C supports arguments -Wno-unused-parameter: YES
      Compiler for C supports arguments -fno-strict-aliasing: YES
      Compiler for C supports arguments -fvisibility=hidden: YES
      Did not find pkg-config by name 'pkg-config'
      Found pkg-config: NO
      Did not find CMake 'cmake'
      Found CMake: NO
      Run-time dependency cairo found: NO (tried framework)

      ../cairo/meson.build:31:12: ERROR: Dependency lookup for cairo with
      method 'pkgconfig' failed: Pkg-config for machine host machine not
      found. Giving up.

      A full log can be found at
      /Users/fred/.cache/uv/sdists-v9/pypi/pycairo/1.28.0/VjMuQu-pihe9WKWKqRcLC/src/.mesonpy-9ta56zsc/meson-logs/meson-log.txt

      hint: This usually indicates a problem with the package or the build
      environment.
  help: `pycairo` (v1.28.0) was included because `svglib` (v1.6.0) depends on
        `rlpycairo` (v0.4.0) which depends on `pycairo`

**Comment by runrunrirun** [comment]
Downgrading the svglib version got it to install, now I have this guy's issue: https://github.com/Acly/krita-ai-diffusion/issues/2132

**Comment by Acly** [comment]
@runrunrirun That would indicate that the install is still not the latest version

Made a new release [v1.41.1](https://github.com/Acly/krita-ai-diffusion/releases/) without the pycairo dependency. That should allow installation to succeed, but you still have to do the server upgrade if it failed before.

If the installer doesn't prompt to upgrade automatically, please try Managed > Re-install

**Comment by runrunrirun** [comment]
That worked - I had to kill an errant process that was binding the server port, probably caused by the previous bad install. Thanks!

**Comment by b4zz4** [comment]
In linux 1.41.1

![Image](https://github.com/user-attachments/assets/fc0d94a1-8aff-4716-b2fa-5f5ba2c4d484)
